---
abstract: 'POE sessions with plain perl calls'
author:
  - 'Philip Gwyn <gwyn -at- cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Session-PlainCall
no_index:
  directory:
    - t
    - inc
requires:
  POE: 1
  Scalar::Util: 0
version: 0.0301
