--- #YAML:1.0
name:               POE-Session-PlainCall
version:            0.0300
abstract:           POE sessions with plain perl calls
author:
    - Philip Gwyn <gwyn-at-pied.nu>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    POE:           1
    Scalar::Util:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
